version: 2.1

orbs:
    codecov: codecov/codecov@4.0.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B -DskipTests clean package
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B test
      - run: mvn jacoco:report
      - run : bash <(curl -s https://codecov.io/bash)
  checkstyle:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target/site/checkstyle
          destination: checkstyle-report
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
      - checkstyle:
          filters:
            branches:
              only:
                - master