version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B -DskipTests clean package
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn test
  codecov:
    uses: codecov/codecov-action@v4
    with:
      verbose: true
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload