version: 2.1

orbs:
    codecov: codecov/codecov@4.0.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B -DskipTests clean package
      - run: mvn checkstyle:check
      - run:
          name: Mettre à jour le README
          command: |
            if [ $? -eq 0 ]; then
              echo -e "![Static Badge](https://img.shields.io/badge/checkstyle-sucess-passing?color=green)" > README.md
            else
              echo -e "![Static Badge](https://img.shields.io/badge/checkstyle-fail-fail?color=red)" > README.md
            fi
      - run:
          name: Commit et push du README
          command: |
            if [[ "$COMMIT_MESSAGE" != *"skip badge"* ]]; then
              git config --global user.email "circleci@example.com"
              git config --global user.name "CircleCI Bot"
              git add README.md
              git commit -m "Met à jour le statut du build dans le README, skip badge"
              git push origin master
            fi
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B test -Dmaven.test.failure.ignore=true
      - run: mvn jacoco:report
      - run : bash <(curl -s https://codecov.io/bash)

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
