version: 2.1

orbs:
    codecov: codecov/codecov@4.0.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B -DskipTests clean package
      - name: Maven run
        run: mvn -B javadoc:javadoc
      - name: Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DOC_TOKEN }}
          publish_dir: ./target/reports/apidocs
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B test -Dmaven.test.failure.ignore=true
      - run: mvn jacoco:report
      - run : bash <(curl -s https://codecov.io/bash)

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master