version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

# Définir les jobs à exécuter pour ce projet
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B -DskipTests clean package
      - run: mvn checkstyle:check
      - run:
          name: Mettre à jour le README
          command: |
            if [ $? -eq 0 ]; then
              echo -e "![Static Badge](https://img.shields.io/badge/checkstyle-sucess-passing?color=green)" >> README.md
            else
              echo -e "![Static Badge](https://img.shields.io/badge/checkstyle-fail-fail?color=red)" >> README.md
            fi

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn -B test -Dmaven.test.failure.ignore=true
      - run: mvn jacoco:report
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master